<?php
declare(strict_types=1);
require __DIR__.'/auth.php';
require_once dirname(__DIR__).'/anmeldung/lib/flow.php';
$slug=(string)($_GET['edition']??'');$ed=x25ed_get($slug);$type=(string)($_GET['typ']??'briefing');
if(!$ed) { xv_page('Edition fehlt','<h1>Edition nicht gefunden.</h1>',404); }
$h=static fn($s):string=>x25ed_e((string)$s);$c=x25_curation_load($slug);$body='';
$title=['briefing'=>'Briefing für Gastgeber und Impulsgeber','platzkarten'=>'Persönliche Platzkarten','kuvert'=>'Dein Kuvert','dossier'=>'Vorbereitung für unsere Runde','papier'=>'Dissenspapier · interne Ausgabe','oeffentlich'=>'Dissenspapier · öffentliche Kurzfassung'][$type]??'Material';
if(in_array($type,['platzkarten','kuvert'],true)) {
    $n=0;foreach(array_reverse(x25_store()->all()) as $rec) {
        if(($rec['edition_slug']??x25_default_slug())!==$slug||$rec['status']!=='zugelassen') { continue; }
        $n++;$number=str_pad((string)$n,2,'0',STR_PAD_LEFT);
        $body.='<section class="sheet"><p class="eyebrow">'.$h($ed['thema']).' · EDITION 01 · PLATZ '.$number.'/25</p><h2>'.$h($rec['name']).'</h2><p>'.$h($rec['company']).'</p>';
        if($type==='platzkarten') { $body.='<p class="serif">'.$h($rec['care']['welcome']??'Schön, dass Du Teil dieser Runde bist.').'</p><p>'.$h($ed['datum_text']).' · Köln, Rheinauhafen</p>'; }
        else { $body.='<h3>Was wird bis zur nächsten Edition eintreten?</h3><div class="write"></div><h3>Wie sicher bist Du Dir? 0–100 %</h3><div class="write short"></div><h3>Welche Entscheidung folgt daraus?</h3><div class="write"></div><p>Datum und Unterschrift</p><div class="write short"></div><p>Du öffnest Dein Kuvert bei der nächsten Edition desselben Themas. Was Du daraus teilst, entscheidest Du.</p>'; }
        $body.='</section>';
    }
    if($type==='kuvert') { $body.='<section class="sheet"><p class="eyebrow">DER 26. EXPERTE</p><h2>Die Vorhersage der KI</h2><p>Dieselbe Frage und derselbe Zeithorizont wie für die Teilnehmer. Werkzeug, Version soweit verfügbar und Zeitpunkt dokumentieren. Die Antwort unverändert einlegen und bis zur nächsten Edition desselben Themas versiegeln.</p><div class="write"></div></section>'; }
    if($body==='') { $body='<p>Für diese Edition sind noch keine Teilnehmer zugelassen.</p>'; }
} elseif($type==='briefing') {
    $body='<h2>Die Runde vorbereiten</h2><p>25 Teilnehmer; höchstens zwei pro Unternehmen. Drei Arbeitstische mit acht bis neun Personen. Gastgeber und Impulsgeber separat zählen. Für jeden Teilnehmer zwei passende Gespräche vorbereiten. Direkte Berichtslinien möglichst auf verschiedene Tische verteilen.</p><h2>Vor dem Treffen</h2><p>Bis zwei Wochen vorher: aktuelle Entscheidung, eigene Erfahrung und Lernfrage einsammeln. Drei Spannungsfelder und zwei Fälle vorbereiten. Dossier vorab freigeben. Persönliche Begrüßung, Platzkarten, Akustik, bequeme Sitzplätze, Catering und Dinner-Sitzordnung prüfen.</p><h2>Vier Formate à 45 Minuten</h2><ol><li>Forschung: 15 Minuten Einordnung, 30 Minuten Diskussion.</li><li>Praxisfall: konkrete Entscheidung, Vorgehen, Ergebnis, ein ehrlicher Lernpunkt.</li><li>Zweiter Fall: Teilnehmer entscheiden zuerst, anschließend tatsächlichen Verlauf betrachten.</li><li>Vorstandsgespräch: Abwägungen und Fragen der Teilnehmer; Austausch danach ermöglichen.</li></ol><h2>KI-Praxistest</h2><p>Entscheidungen der Gruppe dokumentieren, bevor KI-Antworten gezeigt werden. Gleiche Fallinformationen und vorher festgelegte Kriterien verwenden. Werkzeug, Version und Zeitpunkt festhalten. Grenzen benennen; kein wissenschaftlicher Modellvergleich. Keine vertraulichen Unternehmens- oder personenbezogenen Kundendaten eingeben.</p><h2>Vertrauen schützen</h2><p>Chatham House Rule zu Beginn erklären. Ausdrücklich vertrauliche Fallgespräche bleiben auch inhaltlich geschützt. Keine Fotos, Videos oder Aufzeichnungen während der Arbeitsphasen. Fotomomente nur angekündigt beim Empfang und Abend. Partnerrolle offen benennen. Kontakte ausschließlich mit Zustimmung vermitteln.</p><h2>Ergebnisse und Wiedersehen</h2><p>Interne Ausgabe: acht bis zehn Thesen, gemeinsame Positionen, begründete Unterschiede, nächste Schritte und bereinigtes KI-Protokoll. Öffentliche Kurzfassung ausdrücklich freigeben lassen. Persönliche Kuverts versiegeln. Online-Wiedersehen nach sechs Wochen terminieren, persönlich mitteilen und anhand der Umsetzungsfragen moderieren.</p>';
} else {
    $keys=$type==='dossier'?['themes'=>'Drei Spannungsfelder','cases'=>'Zwei vorbereitete Fälle','agenda'=>'Arbeitsagenda']:($type==='papier'?['paper'=>'Gemeinsame Positionen und nächste Schritte']:['public_paper'=>'Ergebnisse der Edition']);
    $released=$type==='dossier'?!empty($c['dossier_ready']):($type==='papier'?!empty($c['paper_ready']):!empty($c['public_paper_approved']));
    if(!$released) { $body='<p class="notice">ENTWURF · noch nicht freigegeben</p>'; }
    foreach($keys as $k=>$label) { $body.='<h2>'.$label.'</h2><div class="copy">'.$h($c[$k]??'Noch nicht ausgearbeitet.').'</div>'; }
    if($type!=='oeffentlich') { $body.='<p>Für den Teilnehmerkreis bestimmt. Vertrauliche Fallgespräche und persönliche Zuordnungen bleiben ausgeschlossen.</p>'; }
}
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store');header('X-Robots-Tag: noindex, nofollow');
echo '<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.$h($title).' · '.$h($ed['name']).'</title><link rel="stylesheet" href="/assets/css/tokens.css"><style>body{background:#FBFAF6;color:#0B1F26;font:16px/1.6 Arial,sans-serif;margin:0}main{max-width:780px;margin:48px auto;padding:32px}header img{width:190px;height:auto}h1,h2{line-height:1.15}h1{font-size:38px}h2{font-size:27px}.eyebrow{font:12px "IBM Plex Mono",monospace;letter-spacing:.1em;color:#0B6470}.serif{font:25px/1.5 "Source Serif 4",Georgia,serif}.sheet{break-after:page;margin:30px 0;padding:30px;border-top:1px solid #DDDAD1}.write{height:120px;border-bottom:1px solid #DDDAD1}.short{height:45px}.copy{white-space:pre-wrap}.notice{color:#C2410C}@media print{body{background:white}main{margin:0;padding:0;max-width:none}.screen{display:none}.sheet{margin:0;padding:25mm 10mm}}@page{size:A4;margin:18mm}</style></head><body><main><header><img src="/assets/img/25experts-logo-horizontal.svg" alt="25 EXPERTS"><p class="eyebrow">'.$h($ed['name']).' · '.$h($ed['datum_text']).'</p><h1>'.$h($title).'</h1><p class="screen">Druckansicht: über die Druckfunktion Deines Browsers drucken oder als PDF speichern. <a href="begleitung.php?edition='.$h($slug).'">Zur Begleitung</a></p></header>'.$body.'</main></body></html>';
